name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x, 1.18.x, 1.19.x]
        arch: [armv6, armv7, aarch64, s390x, ppc64le]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          arch: ${{ matrix.arch }}
          go-version: ${{ matrix.go-version }}

      - name: Test
        run: go test -v ./...